### PR TITLE
refactor(src): apply optimizations

### PR DESCRIPTION
**Pull request by VoltrexMaster**
1. Add missing types.
2. Remove redundant code.
3. Import values as types that are only used for types.
4. Apply a few optimizations.

### CODE REVIEW

**Comment by vierofernando** [comment]
i'll optimize you

**Comment by VoltrexMaster** [comment]
> i'll optimize you

I'll optimize you with a depth of `Infinity`. 💙

**Comment by link-discord** [comment]
sus

**Comment by link-discord** [comment]
Also damn thats a lot of code you changed but I will merge it ig

**Pull request merged**
